/*
** EPITECH PROJECT, 2024
** Zappy
** File description:
** Rules for the server
*/

#pragma once

enum RETURN_CODES {
    CODE_ERROR_MISSING_ARG = -1,
    CODE_ERROR_INVALID_ARG = -2,
    CODE_ERROR_WRONG_FLAG = -3,
    CODE_ERROR_INVALID_NUMBER = -4,
    CODE_ERROR_MALLOC_FAILED = -5,
    CODE_HELP_SUCCESS = 1,
    CODE_SUCCESS = 0,
    CODE_FAILLURE = 84
};

#define MAX_ITEMS 7

#define MICROSECOND_TO_SECOND 1000000
#define MILLISECOND_TO_SECOND 1000
