##
## EPITECH PROJECT, 2024
## AI Zappy
## File description:
## AI Makefile
##

NAME		=	zappy_ai_bonus

all: $(NAME)

$(NAME):
	cp src/main.py $(NAME)
	chmod 775 $(NAME)

clean:
	rm -rf __pycache__

fclean: clean
	rm -f $(NAME)
	rm -f $(TEST_NAME)

re: fclean all
