##
## EPITECH PROJECT, 2024
## AI Zappy
## File description:
## AI Makefile
##

NAME	=	zappy_ai

all: $(NAME)

$(NAME):
	cp src/main.py $(NAME)
	chmod 775 $(NAME)

clean:
	rm -rf __pycache__

fclean: clean
	rm -f $(NAME)

re: fclean all

tests_run:
# TODO #11 (https://github.com/FppEpitech/Zappy/issues/11)
